# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NgzJ653nMS2EZ0Wl9rai4DcwvNHhISHd
"""

import streamlit as st
# Título de la aplicación
st.title('Mi Primera Aplicación Web con Streamlit')
# Texto simple
st.write('Esta es una aplicación web de ejemplo utilizando Streamlit.')